spring:
  application:
    name: my-spring-boot-app
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    mongodb:
      host:
      port: 27017


server:
  port: 8081

jwt:
    secret: 

aws:
  s3:
    bucketName: qa-s3-profile-pic-2
  



logging:
  pattern:
    dateformat: "yyyy-MM-dd'T'HH:mm:ss.SSSZ, America/Chicago"


